const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(p===root)p=path.join(root,'index.html');if(!p.startsWith(root+'/')){res.writeHead(403);return res.end()}fs.readFile(p,(err,data)=>{if(err){res.writeHead(404);res.end('not found');return}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.woff2':'font/woff2'})[path.extname(p)]||'application/octet-stream');res.end(data)})});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});const errors=[];let page;
try{
page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;
await page.goto(base);await page.screenshot({path:path.join(__dirname,'rain-title-desktop.webp')});await page.click('#startBtn');
async function status(){return page.evaluate(()=>({ch:state.ch,phase:state.phase,cursor:state.cursor,inv:state.inv}))}
async function hot(id){await page.locator('[data-hot="'+id+'"]').click()}
async function range(id,v){await page.locator(id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}))},String(v))}
async function advance(target='free'){const s=await status();if(s.phase==='intro'||s.phase==='outro'){const choices=page.locator('#choices .choice');if(await choices.count()){let n=0;if(s.ch===6)n=target==='free'?2:target==='friends'?1:0;await choices.nth(n).click()}else await page.click('#nextBtn')}}
let snapshots=new Set(),savedTest=false;
for(let guard=0;guard<350;guard++){
 const s=await status();if(s.phase==='end')break;
 if(s.ch===3&&s.phase==='intro'&&s.cursor===5){assert.equal(await page.locator('#bg').getAttribute('data-name'),'dinner');await page.evaluate(()=>new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=reject;im.src=ASSET_BASE+'dinner.webp'}));await page.screenshot({path:path.join(__dirname,'rain-dinner-desktop.webp')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'rain-dinner-mobile.webp')});await page.setViewportSize({width:1440,height:1000});await page.reload();await page.click('#continueBtn');assert.equal(await page.locator('#bg').getAttribute('data-name'),'dinner');console.log('DINNER + SCENE RESUME PASS')}
 if(s.phase==='intro'||s.phase==='outro'){if(s.ch===0&&s.phase==='intro'&&s.cursor===0){assert.equal(await page.locator('#bg').getAttribute('data-name'),'club');await page.waitForFunction(()=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im.naturalWidth===2560&&im.naturalHeight===1440);im.onerror=()=>resolve(false);im.src=ASSET_BASE+'club.webp'}));await page.screenshot({path:path.join(__dirname,'rain-boardgame-scene.webp')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'rain-boardgame-scene-mobile.webp')});await page.setViewportSize({width:1440,height:1000});console.log('SPACIOUS BOARDGAME SCENE PASS')}if(s.ch===5&&s.phase==='intro'&&s.cursor===0){assert.equal(await page.locator('#bg').getAttribute('data-name'),'friend-call');await page.waitForFunction(()=>new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im.naturalWidth===2560&&im.naturalHeight===1440);im.onerror=()=>resolve(false);im.src=ASSET_BASE+'friend-call.webp'}));await page.screenshot({path:path.join(__dirname,'rain-friend-call-scene.webp')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'rain-friend-call-scene-mobile.webp')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.setViewportSize({width:1440,height:1000});console.log('FRIEND CALL SCENE PASS')}if(s.ch===5&&s.phase==='outro'&&s.cursor===0){assert.equal(await page.locator('#bg').getAttribute('data-name'),'friend-call')}if(s.ch===3&&s.phase==='intro'&&s.cursor===0){assert.equal(await page.locator('#bg').getAttribute('data-name'),'exhibition');await page.evaluate(()=>new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=reject;im.src=ASSET_BASE+'exhibition.webp'}));await page.screenshot({path:path.join(__dirname,'rain-exhibition-desktop.webp')});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'rain-exhibition-mobile.webp')});await page.setViewportSize({width:1440,height:1000});await page.reload();await page.click('#continueBtn');assert.equal(await page.locator('#bg').getAttribute('data-name'),'exhibition');console.log('EXHIBITION + SCENE RESUME PASS')}if(s.ch===2&&s.phase==='outro'&&(await page.locator('#lineText').innerText()).includes('怎么补偿'))assert.equal(await page.locator('#bg').getAttribute('data-name'),'room');await advance();continue}
 if(s.phase==='finale'){await page.click('#closeModal');await hot('finale');await range('#finalVolume',92);await page.click('#endingBtn');continue}
 if(s.phase==='task'){
 console.log('TASK',s.ch+1);
 if(!snapshots.has(s.ch)){await page.screenshot({path:path.join(__dirname,'rain-ch'+s.ch+'.webp')});snapshots.add(s.ch)}
 if(s.ch===0){assert.equal(await page.locator('#bg').getAttribute('data-name'),'club');await hot('box');assert((await page.locator('#modalBody').innerText()).includes('锁着'));await page.click('#closeModal');await hot('cards');await page.click('#closeModal');await hot('key');await page.click('[data-item="key"]');await hot('box');await page.click('#unlockBtn');assert((await page.locator('#puzzleFeedback').innerText()).includes('没有弹开'));await page.click('[data-wheel="0"]');await page.click('[data-wheel="0"]');await page.click('[data-wheel="2"]');await page.click('#unlockBtn')}
 if(s.ch===1){await hot('ticket');await page.click('#closeModal');await hot('radio');await range('#tune',964);await page.click('#listenBtn');for(const topic of ['band','game','ball','snow']){await page.click('[data-topic="'+topic+'"]');if(topic==='band'){assert.equal(await page.locator('#chatAlbum img').count(),0);for(let j=0;j<7;j++)await page.click('#chatNext');assert.equal(await page.locator('#chatAlbum img').count(),2);assert.equal(await page.locator('.photo-message img').count(),2);await page.waitForFunction(()=>[...document.querySelectorAll('#chatAlbum img,.photo-message img')].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:path.join(__dirname,'rain-festival-chat-desktop.webp')});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.querySelector('#toast').classList.remove('show'));await page.locator('.modal-card').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(__dirname,'rain-festival-chat-mobile.webp')});assert(await page.evaluate(()=>document.querySelector('.modal-card').scrollWidth<=document.querySelector('.modal-card').clientWidth+1));await page.setViewportSize({width:1440,height:1000});await page.reload();await page.click('#continueBtn');await hot('phone');await page.click('[data-topic="band"]');assert.equal(await page.locator('#chatAlbum img').count(),2);assert.equal(await page.evaluate(()=>state.chatProgress.band),7);console.log('FESTIVAL PHOTO MESSAGES + RESUME PASS')}if(topic==='game'){await page.click('#chatNext');await page.click('#chatNext');await page.screenshot({path:path.join(__dirname,'rain-speaker-chat-desktop.webp')});assert.equal(await page.locator('.bubble.me small').first().innerText(),'♡ 女主');assert(!(await page.locator('#modalBody').innerText()).includes('女主 · 我'));assert((await page.locator('#modalBody').innerText()).includes('◇ 男主'));const colors=await page.evaluate(()=>({me:getComputedStyle(document.querySelector('.bubble.me small')).color,him:getComputedStyle(document.querySelector('.bubble.him small')).color,meBg:getComputedStyle(document.querySelector('.bubble.me')).backgroundColor,himBg:getComputedStyle(document.querySelector('.bubble.him')).backgroundColor}));assert(colors.me!==colors.him&&colors.meBg!==colors.himBg);console.log('CHAT SPEAKER COLORS PASS')}for(let k=0;k<35;k++){if(await page.locator('#backTopics').count()){if(topic==='game'){const text=await page.locator('#chatBody').innerText();assert(text.includes('我打野。要不要开把匹配'));assert(text.includes('下路 ADC'));assert(text.includes('我刷完这组野就来下路'));assert(text.includes('有时一个信号'));assert(!text.includes('我可以辅助'));await page.screenshot({path:path.join(__dirname,'rain-jungle-adc-chat.webp')});console.log('JUNGLE + ADC MATCH CHAT PASS')}await page.click('#backTopics');break}if(await page.locator('[data-chat-choice]').count())await page.locator('[data-chat-choice]').first().click();else await page.click('#chatNext')} }await page.click('#meetBtn')}
 if(s.ch===2){if(!savedTest){await page.reload();await page.click('#continueBtn');assert.equal((await status()).ch,2);assert.equal((await status()).phase,'task');savedTest=true}await hot('wiper');await range('#wipe',95);await page.click('#wipeDone');await hot('music');await page.click('[data-song="返场之后"]')}
 if(s.ch===3){assert.equal(await page.locator('#bg').getAttribute('data-name'),'date');await hot('camera');await range('#focus',75);await page.click('#shutter')}
 if(s.ch===4){await hot('pieces');for(const i of [0,1,2,3])await page.click('[data-memory="'+i+'"]');await page.click('#confirmMemory');for(const i of [0,1,2,3])await page.click('[data-flip="'+i+'"]');await page.click('#noMore')}
 if(s.ch===5){await hot('drawers');for(let i=0;i<6;i++){await page.click('[data-sort="'+i+'"]');await page.click('[data-drawer="'+(i%2===0?'his':'mine')+'"]')}await page.click('#closeDrawers')}
 if(s.ch===6){await hot('bag');for(const id of ['raincoat','earplugs','pass'])await page.click('[data-pack="'+id+'"]');await page.click('#packDone')}
 }
}
assert.equal((await status()).phase,'end');assert((await page.locator('.ending h2').innerText()).includes('我先走了'));await page.screenshot({path:path.join(__dirname,'rain-ending-desktop.webp')});console.log('FREE ENDING PASS');
for(const route of ['waiting','friends']){await page.click('#endReplay');for(let guard=0;guard<20;guard++){const s=await status();if(s.phase==='finale'){await range('#finalVolume',100);await page.click('#endingBtn');break}await advance(route)}assert.equal((await status()).phase,'end');console.log(route,'ENDING PASS')}
assert.equal(await page.evaluate(()=>meta.endings.length),3);
await page.click('#endHome');await page.click('#chapterBtn');await page.click('[data-jump="0"]');for(let i=0;i<7;i++)await advance();assert.equal((await status()).phase,'task');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'rain-mobile-task.webp')});await hot('key');await page.click('[data-item="key"]');await hot('box');await page.screenshot({path:path.join(__dirname,'rain-mobile-puzzle.webp')});await page.click('[data-wheel="0"]');await page.click('[data-wheel="0"]');await page.click('[data-wheel="2"]');await page.click('#unlockBtn');await advance();await page.locator('#choices .choice').first().click();const pendingBefore=await page.locator('#lineText').innerText();await page.reload();await page.click('#continueBtn');assert.equal(await page.locator('#lineText').innerText(),pendingBefore);assert.equal(await page.locator('#choices .choice').count(),0);await page.click('#nextBtn');console.log('MOBILE + CHOICE RESUME PASS');
await page.click('#chapterBtn');await page.click('[data-jump="5"]');while((await status()).phase==='intro')await advance();await hot('drawers');await page.screenshot({path:path.join(__dirname,'rain-mobile-drawers.webp')});await page.click('#closeModal');await page.click('#soundBtn');await page.click('#soundBtn');await page.click('#helpBtn');assert.equal(await page.locator('.speaker-legend [data-speaker="女主"]').innerText(),'♡ 女主');assert(!(await page.locator('#modalBody').innerText()).includes('女主 · 我'));assert((await page.locator('#modalBody').innerText()).includes('◇ 男主'));assert((await page.locator('#modalBody').innerText()).includes('✦ 闺蜜'));await page.screenshot({path:path.join(__dirname,'rain-speaker-legend-mobile.webp')});await page.click('#closeModal');
assert.equal(errors.length,0,errors.join('\n'));console.log('ALL TESTS PASSED',JSON.stringify({chapters:snapshots.size,endings:3,resume:true,mobile:true,errors}));
}catch(e){console.error(e);if(page)await page.screenshot({path:path.join(__dirname,'rain-test-failure.webp')});process.exitCode=1}finally{await browser.close();server.close()}})();
